package javaclassparser

import "testing"

const anonymousGenericThisFixture = `class InvariantThisEffects{static String trace="";static Object seen;static boolean fail;static final RuntimeException error=new RuntimeException("identity");}
abstract class InvariantThisBase {final InvariantThisOwner<Object> owner;InvariantThisBase(InvariantThisOwner<Object> owner){InvariantThisEffects.trace+="P";InvariantThisEffects.seen=owner;this.owner=owner;if(InvariantThisEffects.fail)throw InvariantThisEffects.error;}abstract long read();}
class InvariantThisOwner<V>{long seed;final V token;InvariantThisOwner(long seed,V token){this.seed=seed;this.token=token;}final class Gate{boolean same(V candidate){return candidate==token;}}final Gate gate=new Gate();boolean matches(Object candidate){return gate.same((V)candidate);}InvariantThisBase make(){return new InvariantThisBase((InvariantThisOwner)this){long read(){InvariantThisEffects.trace+="R";return owner.seed+InvariantThisOwner.this.seed;}};}}
class InvariantThisDriver{public static void main(String[]a){Object token=new Object();int rows=0;for(long n:new long[]{Long.MIN_VALUE,-1,0,1,Long.MAX_VALUE})for(Object v:new Object[]{null,token})for(boolean fail:new boolean[]{false,true}){InvariantThisOwner<Object> root=new InvariantThisOwner<Object>(n,v);if(!root.matches(v)||root.matches(new Object()))throw new AssertionError("lexical receiver identity");InvariantThisEffects.trace="";InvariantThisEffects.fail=fail;try{InvariantThisBase view=root.make();if(fail||view.owner!=root||InvariantThisEffects.seen!=root||!InvariantThisEffects.trace.equals("P"))throw new AssertionError("constructor identity/order");long expected=java.math.BigInteger.valueOf(n).multiply(java.math.BigInteger.valueOf(2)).longValue();if(view.read()!=expected||!InvariantThisEffects.trace.equals("PR"))throw new AssertionError("word oracle");root.seed+=17;if(view.read()!=java.math.BigInteger.valueOf(root.seed).multiply(java.math.BigInteger.valueOf(2)).longValue())throw new AssertionError("live enclosing receiver");}catch(RuntimeException e){if(!fail||e!=InvariantThisEffects.error||InvariantThisEffects.seen!=root||!InvariantThisEffects.trace.equals("P"))throw new AssertionError("failure identity/evaluation",e);}rows++;}System.out.println(rows+":generic-this:invariant:word:effects:identity");}}`

func TestAdversarialAnonymousGenericThisArgumentPreservesErasedBindingRoundTrip(t *testing.T) {
	testSourceTargetReleaseFamilyFixture(t, anonymousGenericThisFixture, "InvariantThisOwner", "InvariantThisDriver", "20:generic-this:invariant:word:effects:identity\n", "8", []int{8, 11})
}
