package javaclassparser

import (
	"bytes"
	"context"
	"github.com/yaklang/javajive/internal/workbudget"
	"strings"
	"testing"
)

const nativeEmptyArtifactForestFixture = `public class ArtifactForestOwner {
 private final long bias;private ArtifactForestOwner(long bias){this.bias=bias;}
 public interface Value{long get();}
 public class View{private final long seed;private View(long seed){this.seed=seed;}public Value value(final long delta){return new Value(){public long get(){return ArtifactForestOwner.this.bias+View.this.seed+delta;}};}}
 public View make(long seed){return new View(seed);}
 public static ArtifactForestOwner create(long bias){return new ArtifactForestOwner(bias);}
}
class ArtifactForestDriver{public static void main(String[]args){int count=0;for(long bias:new long[]{Long.MIN_VALUE,-1,0,1,Long.MAX_VALUE})for(long seed:new long[]{Long.MIN_VALUE,-1,0,1,Long.MAX_VALUE})for(long delta:new long[]{Long.MIN_VALUE,-1,0,1,Long.MAX_VALUE}){ArtifactForestOwner owner=ArtifactForestOwner.create(bias);ArtifactForestOwner.View view=owner.make(seed);ArtifactForestOwner.Value value=view.value(delta);if(view.getClass().getDeclaringClass()!=ArtifactForestOwner.class||value.getClass().getEnclosingClass()!=ArtifactForestOwner.View.class||!value.getClass().getEnclosingMethod().getName().equals("value"))throw new AssertionError("named/anonymous ownership");long want=java.math.BigInteger.valueOf(bias).add(java.math.BigInteger.valueOf(seed)).add(java.math.BigInteger.valueOf(delta)).longValue();if(value.get()!=want)throw new AssertionError("capture/binding/overflow");count++;}System.out.println(count+":marker:named:anonymous:overflow");}}
`

// A compiler-only private-constructor marker is not a lexical anonymous
// object. It is regenerated by the existing bridge protocol, independently
// from the real anonymous body nested in the named member.
func TestAdversarialMemberEmptyArtifactDoesNotCreateAnonymousScope(t *testing.T) {
	for _, root := range []string{"ArtifactForestOwner", "RenamedForestOwner"} {
		source := nativeEmptyArtifactForestFixture
		source = strings.ReplaceAll(source, "ArtifactForestOwner", root)
		t.Run(root, func(t *testing.T) {
			testNativePrivateSetterCompiledFixture(t, root, "ArtifactForestDriver", "125:marker:named:anonymous:overflow\n", func(t *testing.T, debug string) map[string][]byte {
				return nativeCompileSourceReleaseClasses(t, map[string]string{root + ".java": source}, debug, "8")
			})
		})
	}
}

// Discovery excludes only a declared and still-valid original bridge artifact.
// An unchanged unnamed row, forged cached role, or flags alone are insufficient.
func TestAdversarialMemberEmptyArtifactDiscoveryBoundaries(t *testing.T) {
	for _, debug := range []string{"none", "source,lines,vars"} {
		files := nativeCompileSourceReleaseClasses(t, map[string]string{"ArtifactEvidence.java": `public class ArtifactEvidence{private long value;class Child{private Child(long x){value=x;}Object make(){return new Object(){long get(){return value;}};}}Child create(long x){return new Child(x);}}`}, debug, "8")
		for _, variant := range []string{"original", "no ownership plan", "missing owned marker", "wrong root", "resolved flags changed", "resolved field added", "work", "canceled"} {
			t.Run(debug+"/"+variant, func(t *testing.T) {
				original := map[string][]byte{}
				for name, raw := range files {
					original[name] = bytes.Clone(raw)
				}
				z := nativeArchive(t, original)
				defer z.Close()
				root, e := Parse(bytes.Clone(original["ArtifactEvidence.class"]))
				if e != nil {
					t.Fatal(e)
				}
				d := z.nativeMemberReader(root)
				p := d.planNativeMemberFamily()
				if p == nil || p.emptyMarkers["ArtifactEvidence$1"] == nil {
					t.Fatal("genuine compiler marker not owned")
				}
				wantHas, wantClosed := false, true
				switch variant {
				case "no ownership plan":
					p = nil
					wantHas = true
				case "missing owned marker":
					p.emptyMarkers = nil
					wantHas = true
				case "wrong root":
					p.owner = "ForeignRoot"
					wantHas = true
				case "resolved flags changed", "resolved field added":
					marker, e := Parse(bytes.Clone(original["ArtifactEvidence$1.class"]))
					if e != nil {
						t.Fatal(e)
					}
					if variant == "resolved flags changed" {
						marker.AccessFlags = 0x0020
					} else {
						marker.ConstantPool = append(marker.ConstantPool, &ConstantUtf8Info{Value: "value"}, &ConstantUtf8Info{Value: "J"})
						marker.Fields = append(marker.Fields, &MemberInfo{AccessFlags: 2, NameIndex: uint16(len(marker.ConstantPool) - 1), DescriptorIndex: uint16(len(marker.ConstantPool))})
					}
					original["ArtifactEvidence$1.class"] = marker.Bytes()
					d.foldSiblingResolver = func(name string) ([]byte, bool) { raw, ok := original[name+".class"]; return raw, ok }
					wantHas = true
				case "work":
					d.Work = workbudget.New(context.Background(), workbudget.Limits{MaxRequestWork: 1})
					wantClosed = false
				case "canceled":
					ctx, cancel := context.WithCancel(context.Background())
					cancel()
					d.Work = workbudget.New(ctx, workbudget.Limits{})
					wantClosed = false
				}
				has, closed := d.nativeAnonymousForestHasChildren(p)
				if has != wantHas || closed != wantClosed {
					t.Fatalf("has=%v closed=%v want=%v/%v", has, closed, wantHas, wantClosed)
				}
			})
		}
	}
}
