package javaclassparser

import "testing"

// Every exceptional edge observes the locals immediately before its throw site.
// A throwing RHS must not commit its store; catch/finally must read the same
// original slot web, including its nonzero/reference definition before the try.
func TestAdversarialExceptionBeforeStateLocalWebRoundTrip(t *testing.T) {
	roundTripGenericFlowUnits(t, "BeforeStateDriver", `import java.io.*;
class BeforeStateEffects{static String trace="";static final IllegalArgumentException runtime=new IllegalArgumentException("identity");static final IOException checked=new IOException("identity");static final AssertionError error=new AssertionError("identity");static final Object initial=new Object(),first=new Object(),second=new Object();static void fail(int mode,int stage)throws IOException{trace+=(char)('A'+stage);if(mode==stage)throw runtime;if(mode==stage+10)throw checked;if(mode==stage+20)throw error;}static int number(int mode,int stage)throws IOException{fail(mode,stage);return stage==1?101:202;}static long wide(int mode,int stage)throws IOException{fail(mode,stage);return stage==1?4294967297L:-4294967298L;}static Object object(int mode,int stage)throws IOException{fail(mode,stage);return stage==1?first:second;}static void remember(Throwable failure){trace+=(failure==runtime?"R":failure==checked?"C":failure==error?"E":"?");}}
class BeforeStateConsumer{
 static int integer(int mode){int value=37;try{BeforeStateEffects.fail(mode,0);value=BeforeStateEffects.number(mode,1);BeforeStateEffects.fail(mode,2);value=BeforeStateEffects.number(mode,3);return value;}catch(IllegalArgumentException failure){BeforeStateEffects.remember(failure);return value;}catch(IOException failure){BeforeStateEffects.remember(failure);return -value;}finally{BeforeStateEffects.trace+="F";}}
 static long wide(int mode){long value=-7000000003L;try{BeforeStateEffects.fail(mode,0);value=BeforeStateEffects.wide(mode,1);BeforeStateEffects.fail(mode,2);value=BeforeStateEffects.wide(mode,3);return value;}catch(IllegalArgumentException failure){BeforeStateEffects.remember(failure);return value;}catch(IOException failure){BeforeStateEffects.remember(failure);return -value;}finally{BeforeStateEffects.trace+="F";}}
 static Object reference(int mode){Object value=BeforeStateEffects.initial;try{BeforeStateEffects.fail(mode,0);value=BeforeStateEffects.object(mode,1);BeforeStateEffects.fail(mode,2);value=BeforeStateEffects.object(mode,3);return value;}catch(IllegalArgumentException failure){BeforeStateEffects.remember(failure);return value;}catch(IOException failure){BeforeStateEffects.remember(failure);return value;}finally{BeforeStateEffects.trace+="F";}}
 static int effectSeed(int mode)throws IOException{int value=BeforeStateEffects.number(mode,0);try{value=11;BeforeStateEffects.fail(mode,1);value=-7;BeforeStateEffects.fail(mode,2);return 3;}catch(IllegalArgumentException failure){return value;}catch(IOException failure){return value;}}
 static int literalSeed(int mode){int value=91;try{value=11;BeforeStateEffects.fail(mode,1);value=-7;BeforeStateEffects.fail(mode,2);return 3;}catch(IllegalArgumentException failure){return value;}catch(IOException failure){return value;}}
 static long longSeed(int mode){long value=-7000000003L;try{value=4294967297L;BeforeStateEffects.fail(mode,1);value=-4294967298L;BeforeStateEffects.fail(mode,2);return 3;}catch(IllegalArgumentException failure){return value;}catch(IOException failure){return value;}}
 static Object refSeed(int mode){Object value=BeforeStateEffects.initial;try{value=BeforeStateEffects.first;BeforeStateEffects.fail(mode,1);value=BeforeStateEffects.second;BeforeStateEffects.fail(mode,2);return value;}catch(IllegalArgumentException failure){return value;}catch(IOException failure){return value;}}
 static int minimal(int mode){int value=0;try{value=1;BeforeStateEffects.fail(mode,1);value=2;BeforeStateEffects.fail(mode,2);return 3;}catch(IllegalArgumentException failure){return value;}catch(IOException failure){return value;}}
}
class BeforeStateObserver{static void run(){for(int mode:new int[]{-1,0,1,2,3,10,11,12,13,20,21,22,23}){BeforeStateEffects.trace="";try{System.out.println("i:"+BeforeStateConsumer.integer(mode)+":"+BeforeStateEffects.trace);}catch(Throwable failure){System.out.println("i:"+(failure==BeforeStateEffects.error)+":"+BeforeStateEffects.trace);}BeforeStateEffects.trace="";try{System.out.println("l:"+BeforeStateConsumer.wide(mode)+":"+BeforeStateEffects.trace);}catch(Throwable failure){System.out.println("l:"+(failure==BeforeStateEffects.error)+":"+BeforeStateEffects.trace);}BeforeStateEffects.trace="";try{Object value=BeforeStateConsumer.reference(mode);System.out.println("o:"+(value==BeforeStateEffects.initial)+":"+(value==BeforeStateEffects.first)+":"+(value==BeforeStateEffects.second)+":"+BeforeStateEffects.trace);}catch(Throwable failure){System.out.println("o:"+(failure==BeforeStateEffects.error)+":"+BeforeStateEffects.trace);}BeforeStateEffects.trace="";try{System.out.println("seed-effect:"+BeforeStateConsumer.effectSeed(mode)+":"+BeforeStateEffects.trace);}catch(Throwable failure){System.out.println("seed-effect:"+(failure==BeforeStateEffects.runtime)+":"+(failure==BeforeStateEffects.checked)+":"+(failure==BeforeStateEffects.error)+":"+BeforeStateEffects.trace);}BeforeStateEffects.trace="";try{System.out.println("s:"+BeforeStateConsumer.literalSeed(mode)+":"+BeforeStateConsumer.longSeed(mode)+":"+(BeforeStateConsumer.refSeed(mode)==BeforeStateEffects.first)+":"+BeforeStateEffects.trace);}catch(Throwable failure){System.out.println("s:"+(failure==BeforeStateEffects.error)+":"+BeforeStateEffects.trace);}BeforeStateEffects.trace="";try{System.out.println("m:"+BeforeStateConsumer.minimal(mode)+":"+BeforeStateEffects.trace);}catch(Throwable failure){System.out.println("m:"+(failure==BeforeStateEffects.error)+":"+BeforeStateEffects.trace);}}}}
public class BeforeStateDriver{public static void main(String[]args){BeforeStateObserver.run();}}
`, nil, []string{"BeforeStateConsumer"}, Precision, Compatibility, "legacy")
}
