package javaclassparser

import (
	"github.com/yaklang/javajive/classparser/decompiler/core"
	"github.com/yaklang/javajive/classparser/decompiler/core/class_context"
	"github.com/yaklang/javajive/classparser/decompiler/core/values"
	"github.com/yaklang/javajive/classparser/decompiler/core/values/types"
	"github.com/yaklang/javajive/internal/workbudget"
	"strings"
)

// A descriptor is source-only projected under one joint lexical ownership plan.
// Matching a numeric type name is insufficient: the constructor body must be
// the proved private delegate, and its marker must be regenerated by that plan.
func nativeMemberJointBridgeDeclaration(p *nativeMemberFamily, obj *ClassObject, m *MemberInfo, marker string, work *workbudget.Budget) bool {
	if p == nil || obj == nil || m == nil || !nativeProofWork(work, 1) {
		return false
	}
	child := p.children[obj.GetClassName()]
	if child == nil {
		return false
	}
	name, nok := sourceBridgeUTF8(obj, m.NameIndex)
	desc, dok := sourceBridgeUTF8(obj, m.DescriptorIndex)
	b := child.accessBridges[desc]
	return nok && dok && name == "<init>" && b != nil && b.marker == marker && nativeMemberBridgeEquivalent(child, obj, m, desc, work)
}
func nativeMemberBridgeEquivalent(child *nativeMemberClass, obj *ClassObject, m *MemberInfo, desc string, work *workbudget.Budget) bool {
	reader := NewClassObjectDumper(obj)
	reader.Work = work
	fresh := reader.nativeConstructorAccessBridges()[desc]
	b := child.accessBridges[desc]
	return fresh != nil && b != nil && fresh.method == m && fresh.target == b.target && fresh.marker == b.marker
}
func nativeMemberJointBridgeNameTypes(p *nativeMemberFamily, obj *ClassObject, work *workbudget.Budget) map[int]bool {
	out := map[int]bool{}
	if p == nil {
		return out
	}
	for name, child := range p.children {
		if child == nil {
			return nil
		}
		if len(child.accessBridges) == 0 {
			continue
		}
		if !nativeProofWork(work, 1) {
			return nil
		}
		proof := &nativeAnonymousFamily{owner: name, bridges: child.accessBridges}
		for index, valid := range proof.accessBridgeNameTypes(obj, work) {
			if valid {
				out[index] = true
			}
		}
	}
	return out
}
func nativeMemberJointBridgeMarkersClosed(p *nativeMemberFamily, work *workbudget.Budget) bool {
	if p == nil {
		return false
	}
	for _, child := range p.children {
		if child == nil {
			return false
		}
		for _, bridge := range child.accessBridges {
			if !nativeProofWork(work, 1) || !child.static || p.anonymous == nil {
				return false
			}
			marker := p.anonymous.children[bridge.marker]
			if marker == nil || marker.ordinal != 1 || p.anonymous.owner != p.owner || marker.object.GetClassName() != bridge.marker {
				return false
			}
		}
	}
	return true
}
func nativeMemberStaticBridgeAllocation(obj *ClassObject, ops []*core.OpCode, i int, child *nativeMemberClass, work *workbudget.Budget) (*nativeMemberAllocation, bool) {
	if i+2 >= len(ops) || ops[i+1].Instr.OpCode != core.OP_DUP {
		return nil, false
	}
	for j := i + 2; j < len(ops); j++ {
		if !nativeProofWork(work, 1) {
			return nil, false
		}
		op := ops[j]
		call := constructorMotionMember(obj, op, core.OP_INVOKESPECIAL)
		if call != nil && call.Member == "<init>" && call.Name == child.object.GetClassName() {
			bridge := child.accessBridges[call.Description]
			if bridge == nil {
				return nil, true
			}
			if j == i+2 || ops[j-1].Instr.OpCode != core.OP_ACONST_NULL || len(ops[j-1].Data) != 0 {
				return nil, false
			}
			return &nativeMemberAllocation{child: child, descriptor: call.Description, newPC: int(ops[i].CurrentOffset), invokePC: int(op.CurrentOffset), checkPC: -1, enclosingReadPC: -1}, true
		}
		if op.Instr.OpCode == core.OP_NEW || op.Instr.OpCode == core.OP_GOTO || op.Instr.OpCode == core.OP_RETURN || op.Instr.OpCode == core.OP_ARETURN {
			return nil, false
		}
	}
	return nil, false
}
func nativeMemberJointBridgeCallersClosed(p *nativeMemberFamily, obj *ClassObject, allocations map[string]map[int]*nativeMemberAllocation, work *workbudget.Budget) bool {
	if p == nil || obj == nil {
		return false
	}
	has := false
	for _, child := range p.children {
		if child != nil && len(child.accessBridges) > 0 {
			has = true
			break
		}
	}
	if !has {
		return true
	}
	for _, m := range obj.Methods {
		for _, a := range m.Attributes {
			code, ok := a.(*CodeAttribute)
			if !ok {
				continue
			}
			if !nativeProofWork(work, int64(len(code.Code))) {
				return false
			}
			d := core.NewDecompiler(code.Code, func(i int) values.JavaValue { return GetValueFromCP(obj.ConstantPool, i) })
			d.Work = work
			if d.ParseOpcode() != nil {
				return false
			}
			name, _ := obj.getUtf8(m.NameIndex)
			desc, _ := obj.getUtf8(m.DescriptorIndex)
			for _, op := range d.Opcodes() {
				call := constructorMotionMember(obj, op, core.OP_INVOKESPECIAL)
				if call == nil || call.Member != "<init>" {
					continue
				}
				child := p.children[call.Name]
				if child == nil || child.accessBridges[call.Description] == nil {
					continue
				}
				// A flat foreign source unit cannot reproduce a Java private lexical call.
				if obj.GetClassName() != p.owner && p.children[obj.GetClassName()] == nil && p.anonymousUnits[obj.GetClassName()] == nil {
					return false
				}
				plan := allocations[name+desc][int(op.CurrentOffset)]
				if plan == nil || plan.child != child || plan.descriptor != call.Description {
					return false
				}
				if p.bridgeCalls == nil {
					p.bridgeCalls = map[string]int{}
				}
				p.bridgeCalls[call.Name+call.Description]++
			}
		}
	}
	return true
}
func nativeMemberStaticBridgeSource(plan *nativeMemberAllocation, args []class_context.SourceCaptureOperand, ctx, binding *class_context.ClassContext, p *nativeMemberFamily) (string, bool) {
	fail := func() (string, bool) {
		if p != nil {
			p.failed = true
		}
		return "", false
	}
	if plan == nil || plan.child == nil || p == nil || ctx == nil || binding == nil {
		return fail()
	}
	bridge := plan.child.accessBridges[plan.descriptor]
	if bridge == nil || len(args) == 0 {
		return fail()
	}
	last, ok := args[len(args)-1].Value.(values.JavaValue)
	if !ok {
		return fail()
	}
	literal, ok := values.UnpackSoltValue(last).(*values.JavaLiteral)
	if !ok || literal == nil || literal.Data != "null" || len(literal.Units) != 0 {
		return fail()
	}
	invoke := &values.FunctionCallExpression{ClassName: strings.ReplaceAll(plan.child.object.GetClassName(), "/", "."), FunctionName: "<init>", Descriptor: bridge.target, Kind: values.InvokeSpecial, IsSpecialInvoke: true, HasOriginPC: true, OriginPC: plan.invokePC}
	for _, arg := range args[:len(args)-1] {
		v, ok := arg.Value.(values.JavaValue)
		if !ok {
			return fail()
		}
		invoke.Arguments = append(invoke.Arguments, v)
	}
	mt, e := types.ParseMethodDescriptor(bridge.target)
	if e != nil || len(mt.FunctionType().ParamTypes) != len(invoke.Arguments) {
		return fail()
	}
	invoke.FuncType = mt.FunctionType()
	allocationBinding := *ctx
	allocationBinding.InvocationMetadata = binding.InvocationMetadata
	allocationBinding.SiblingClassSig = binding.SiblingClassSig
	arguments := invoke.ArgumentStrings(&allocationBinding)
	name := ctx.ShortTypeName(invoke.ClassName)
	if plan.child.formalCount > 0 {
		name += "<>"
	}
	return "new " + name + "(" + strings.Join(arguments, ",") + ")", true
}

// Original archive users of a marker must all remain inside the committed
// lexical family. Method handles and source-spellable marker declarations are
// not unused compiler arguments, even when their erasures happen to match.
func (z *JarFS) nativeMemberJointBridgeReferencesClosed(p *nativeMemberFamily, index *nativeMemberIndex, work *workbudget.Budget) bool {
	markers := map[string]bool{}
	for _, child := range p.children {
		for _, bridge := range child.accessBridges {
			markers[bridge.marker] = true
		}
	}
	users := map[string]bool{}
	for marker := range markers {
		for user := range index.typeUsers[marker] {
			users[user] = true
		}
	}
	for user := range users {
		if !nativeProofWork(work, 1) {
			return false
		}
		if user != p.owner && p.children[user] == nil && p.anonymousUnits[user] == nil {
			return false
		}
		raw, ok := z.enumSiblingResolver()(user)
		if !ok {
			return false
		}
		reader := z.nativeMemberReader(nil)
		obj, err := reader.parseResolved(raw)
		if err != nil || obj.GetClassName() != user {
			return false
		}
		allowed := nativeMemberJointBridgeNameTypes(p, obj, work)
		for i, constant := range obj.ConstantPool {
			if !nativeProofWork(work, 1) {
				return false
			}
			if nt, ok := constant.(*ConstantNameAndTypeInfo); ok && nt != nil {
				desc, known := sourceBridgeUTF8(obj, nt.DescriptorIndex)
				if !known {
					return false
				}
				for marker := range markers {
					if strings.Contains(desc, "L"+marker+";") && !allowed[i+1] {
						return false
					}
				}
			}
		}
		for _, member := range append(append([]*MemberInfo{}, obj.Fields...), obj.Methods...) {
			desc, ok := sourceBridgeUTF8(obj, member.DescriptorIndex)
			if !ok {
				return false
			}
			for marker := range markers {
				if strings.Contains(desc, "L"+marker+";") && !nativeMemberJointBridgeDeclaration(p, obj, member, marker, work) {
					return false
				}
			}
		}
		for _, m := range obj.Methods {
			for _, a := range m.Attributes {
				code, ok := a.(*CodeAttribute)
				if !ok {
					continue
				}
				if !nativeProofWork(work, int64(len(code.Code))) {
					return false
				}
				d := core.NewDecompiler(code.Code, func(i int) values.JavaValue { return GetValueFromCP(obj.ConstantPool, i) })
				d.Work = work
				if d.ParseOpcode() != nil {
					return false
				}
				for _, op := range d.Opcodes() {
					var name string
					var known bool
					switch op.Instr.OpCode {
					case core.OP_NEW, core.OP_CHECKCAST, core.OP_INSTANCEOF, core.OP_ANEWARRAY, core.OP_MULTIANEWARRAY:
						if len(op.Data) < 2 {
							return false
						}
						name, known = sourceBridgeClassName(obj, core.Convert2bytesToInt(op.Data[:2]))
					case core.OP_LDC:
						if len(op.Data) != 1 {
							return false
						}
						name, known = sourceBridgeClassName(obj, uint16(op.Data[0]))
					case core.OP_LDC_W:
						if len(op.Data) != 2 {
							return false
						}
						name, known = sourceBridgeClassName(obj, core.Convert2bytesToInt(op.Data))
					}
					if known && markers[name] {
						child := p.anonymous.children[name]
						if op.Instr.OpCode != core.OP_NEW || user != p.owner || child == nil || child.newPC != int(op.CurrentOffset) {
							return false
						}
					}
				}
			}
		}
	}
	return true
}
