package javaclassparser

// A final anonymous binary cannot be regenerated by a modern anonymous
// expression. Its existing independent declaration can nevertheless own a
// native child expression. This certificate licenses only that source boundary;
// it does not turn the original anonymous class into a top-level lexical owner
// or allow its constructor's early capture stores to cross an observing SUPER.
type nativeAnonymousIndependentRoot struct {
	object       *ClassObject
	lexicalOwner string
	method       string
}

func (c *ClassObjectDumper) originalNativeAnonymousIndependentRoot() *nativeAnonymousIndependentRoot {
	if c == nil || c.obj == nil || c.foldSiblingResolver == nil {
		return nil
	}
	owner, method, known := originalAnonymousOwner(c.obj)
	if !known || owner == c.obj.GetClassName() || method == "" {
		return nil
	}
	raw, found := c.foldSiblingResolver(owner)
	if !found {
		return nil
	}
	original, err := c.parseResolved(raw)
	if err != nil || original.GetClassName() != owner {
		return nil
	}
	reader := NewClassObjectDumper(original)
	reader.options = c.options
	reader.Work = c.Work
	reader.foldSiblingResolver = c.foldSiblingResolver
	reader.declarationResolver = c.declarationResolver
	// Reuse the independently proved flat-tail domain: final header, exact
	// static owning method, closed binders and original capture packet, with an
	// inert no-argument superclass constructor on the selected runtime profiles.
	standalone := &nativeAnonymousFamily{owner: owner, children: map[string]*nativeAnonymousClass{}, standalone: map[string]*ClassObject{c.obj.GetClassName(): c.obj}}
	if !reader.nativeAnonymousStandaloneTailClosed(standalone, nil, nil, reader.buildInvocationMetadata(), reader.originalNativeConstructorAccessBridges()) {
		return nil
	}
	return &nativeAnonymousIndependentRoot{object: c.obj, lexicalOwner: owner, method: method}
}

func (p *nativeAnonymousIndependentRoot) validFor(c *ClassObjectDumper) bool {
	if p == nil || c == nil || c.obj != p.object {
		return false
	}
	// Re-read original ownership/declarations; a cached packet or same-spelled
	// method cannot substitute for the original complete constructor proof.
	fresh := c.originalNativeAnonymousIndependentRoot()
	return fresh != nil && fresh.lexicalOwner == p.lexicalOwner && fresh.method == p.method
}
