package javaclassparser

import (
	"github.com/yaklang/javajive/classparser/decompiler/core"
	"github.com/yaklang/javajive/classparser/decompiler/core/class_context"
	"github.com/yaklang/javajive/classparser/decompiler/core/values"
	"github.com/yaklang/javajive/classparser/decompiler/core/values/types"
	"github.com/yaklang/javajive/internal/workbudget"
	"sort"
	"strings"
)

// A descriptor is source-only projected under one joint lexical ownership plan.
// Matching a numeric type name is insufficient: the constructor body must be
// the proved private delegate, and its marker must be regenerated by that plan.
func nativeMemberJointBridgeDeclaration(p *nativeMemberFamily, obj *ClassObject, m *MemberInfo, marker string, work *workbudget.Budget) bool {
	if p == nil || obj == nil || m == nil || !nativeProofWork(work, 1) {
		return false
	}
	bridges := p.constructorBridges(obj.GetClassName())
	name, nok := sourceBridgeUTF8(obj, m.NameIndex)
	desc, dok := sourceBridgeUTF8(obj, m.DescriptorIndex)
	b := bridges[desc]
	return nok && dok && name == "<init>" && b != nil && b.marker == marker && nativeMemberJointBridgeEquivalent(p, obj, m, desc, work)
}
func nativeMemberJointBridgeNameTypes(p *nativeMemberFamily, obj *ClassObject, work *workbudget.Budget) map[int]bool {
	if p == nil {
		return map[int]bool{}
	}
	for _, child := range p.children {
		if child == nil || !nativeProofWork(work, 1) {
			return nil
		}
	}
	return nativeConstructorBridgeNameTypes(obj, p.bridgeOwners(), work)
}
func nativeMemberJointBridgeMarkersClosed(p *nativeMemberFamily, work *workbudget.Budget) bool {
	if p == nil {
		return false
	}
	for owner, bridges := range p.bridgeOwners() {
		child := p.children[owner]
		if owner != p.owner && child == nil {
			return false
		}
		for _, bridge := range bridges {
			if bridge == nil || !nativeProofWork(work, 1) || child != nil && !child.static && child.constructors[bridge.target] == nil {
				return false
			}
			if marker := p.emptyMarkers[bridge.marker]; marker != nil && nativeMemberEmptyAccessMarker(marker, p.owner, work) {
				continue
			}
			if nativeMemberJointSwitchTableMarker(p, bridge.marker, work) {
				continue
			}
			if p.anonymous == nil {
				return false
			}
			marker := p.anonymous.children[bridge.marker]
			if marker == nil || marker.object == nil || marker.ordinal != 1 || p.anonymous.owner != p.owner || marker.object.GetClassName() != bridge.marker {
				return false
			}
		}
	}
	return true
}
func nativeMemberStaticBridgeAllocation(obj *ClassObject, ops []*core.OpCode, i int, child *nativeMemberClass, work *workbudget.Budget, origins ...map[int]nativeMemberAllocationInvocation) (*nativeMemberAllocation, bool) {
	if child == nil || child.object == nil {
		return nil, false
	}
	plan, ok := nativeBridgeAllocation(obj, ops, i, child.object, child.accessBridges, work, origins...)
	if plan != nil {
		plan.child = child
	}
	return plan, ok
}

func nativeRootBridgeAllocation(obj *ClassObject, ops []*core.OpCode, i int, root *ClassObject, bridges map[string]*nativeConstructorAccessBridge, work *workbudget.Budget, origins ...map[int]nativeMemberAllocationInvocation) (*nativeMemberAllocation, bool) {
	plan, ok := nativeBridgeAllocation(obj, ops, i, root, bridges, work, origins...)
	if plan != nil {
		plan.rootObject = root
	}
	return plan, ok
}

// Discovery records the original NEW and constructor call sites. The source
// renderer independently requires the IR's uninitialized allocation origin;
// finding a same-owner call alone never establishes receiver identity.
func nativeBridgeAllocation(obj *ClassObject, ops []*core.OpCode, i int, target *ClassObject, bridges map[string]*nativeConstructorAccessBridge, work *workbudget.Budget, origins ...map[int]nativeMemberAllocationInvocation) (*nativeMemberAllocation, bool) {
	if obj == nil || target == nil || i < 0 || i+2 >= len(ops) || ops[i].Instr.OpCode != core.OP_NEW || ops[i+1].Instr.OpCode != core.OP_DUP {
		return nil, false
	}
	owner, known := sourceBridgeClassName(obj, core.Convert2bytesToInt(ops[i].Data))
	if !known || owner != target.GetClassName() {
		return nil, false
	}
	if len(origins) > 0 {
		// A nested NEW may initialize another object with this same nominal
		// owner. Only the immutable verifier type and SSA origin identify the
		// matching receiver. The source hook independently seals both PCs.
		if len(origins) != 1 || !nativeProofWork(work, 1) {
			return nil, false
		}
		invocation, found := origins[0][int(ops[i].CurrentOffset)]
		if !found || invocation.owner != owner || invocation.pc <= int(ops[i+1].CurrentOffset) {
			return nil, false
		}
		j := sort.Search(len(ops), func(j int) bool { return int(ops[j].CurrentOffset) >= invocation.pc })
		if j >= len(ops) || int(ops[j].CurrentOffset) != invocation.pc {
			return nil, false
		}
		call := constructorMotionMember(obj, ops[j], core.OP_INVOKESPECIAL)
		if call == nil || call.Member != "<init>" || call.Name != owner || call.Description != invocation.descriptor {
			return nil, false
		}
		if bridges[call.Description] == nil {
			return nil, true
		}
		if j <= i+2 || ops[j-1].Instr.OpCode != core.OP_ACONST_NULL || len(ops[j-1].Data) != 0 {
			return nil, false
		}
		return &nativeMemberAllocation{descriptor: call.Description, newPC: int(ops[i].CurrentOffset), invokePC: invocation.pc, checkPC: -1, enclosingReadPC: -1}, true
	}
	for j := i + 2; j < len(ops); j++ {
		if !nativeProofWork(work, 1) {
			return nil, false
		}
		op := ops[j]
		call := constructorMotionMember(obj, op, core.OP_INVOKESPECIAL)
		if call != nil && call.Member == "<init>" && call.Name == owner {
			if bridges[call.Description] == nil {
				return nil, true
			}
			if j == i+2 || ops[j-1].Instr.OpCode != core.OP_ACONST_NULL || len(ops[j-1].Data) != 0 {
				return nil, false
			}
			return &nativeMemberAllocation{descriptor: call.Description, newPC: int(ops[i].CurrentOffset), invokePC: int(op.CurrentOffset), checkPC: -1, enclosingReadPC: -1}, true
		}
		if op.Instr.OpCode == core.OP_NEW || op.Instr.OpCode == core.OP_GOTO || op.Instr.OpCode == core.OP_RETURN || op.Instr.OpCode == core.OP_ARETURN {
			return nil, false
		}
	}
	return nil, false
}
func nativeMemberJointBridgeCallersClosed(p *nativeMemberFamily, obj *ClassObject, allocations map[string]map[int]*nativeMemberAllocation, work *workbudget.Budget) bool {
	if p == nil || obj == nil {
		return false
	}
	has := false
	for _, bridges := range p.bridgeOwners() {
		if len(bridges) > 0 {
			has = true
			break
		}
	}
	if !has {
		return true
	}
	for _, m := range obj.Methods {
		for _, a := range m.Attributes {
			code, ok := a.(*CodeAttribute)
			if !ok {
				continue
			}
			if !nativeProofWork(work, int64(len(code.Code))) {
				return false
			}
			d := core.NewDecompiler(code.Code, func(i int) values.JavaValue { return GetValueFromCP(obj.ConstantPool, i) })
			d.Work = work
			if d.ParseOpcode() != nil {
				return false
			}
			name, _ := obj.getUtf8(m.NameIndex)
			desc, _ := obj.getUtf8(m.DescriptorIndex)
			for _, op := range d.Opcodes() {
				call := constructorMotionMember(obj, op, core.OP_INVOKESPECIAL)
				if call == nil || call.Member != "<init>" {
					continue
				}
				child := p.children[call.Name]
				if p.constructorBridges(call.Name)[call.Description] == nil {
					continue
				}
				// A source call from the declaring class invokes the private
				// target directly. It cannot retain this original synthetic
				// invocation, even if another lexical caller needs that bridge.
				if obj.GetClassName() == call.Name {
					return false
				}
				// A flat foreign source unit cannot reproduce a Java private lexical call.
				if obj.GetClassName() != p.owner && p.children[obj.GetClassName()] == nil && p.anonymousUnits[obj.GetClassName()] == nil && p.enumConstants[obj.GetClassName()] == nil {
					// A named method-local belongs to its proved EnclosingMethod
					// scope. It remains a distinct declaration role; the exact
					// local object, capture packet and lexical owner chain must
					// close before its original NEW can use this private bridge.
					if _, known := nativeMemberJointMethodLocalOwner(p, obj, work); !known {
						return false
					}
				}
				plan := allocations[name+desc][int(op.CurrentOffset)]
				allocation := plan != nil && plan.allocatedObject() != nil && plan.allocatedObject().GetClassName() == call.Name && plan.descriptor == call.Description && (child != nil && plan.child == child || call.Name == p.owner && plan.rootObject == p.lexicalObjects[p.owner])
				super := false
				if caller := p.children[obj.GetClassName()]; caller != nil && name == "<init>" && !caller.static {
					ctor := caller.constructors[desc]
					super = ctor != nil && ctor.projectedSuper && caller.object.GetSupperClassName() == call.Name && ctor.delegateOwner == call.Name && ctor.delegateDescriptor == call.Description && ctor.delegatePC == int(op.CurrentOffset)
				}
				// Only a NEW origin or an independently verified initial
				// lexical SUPER delegation regenerates the private bridge.
				rootSuper := p.rootBridgeDelegation(obj, name, desc, call.Name, call.Description, int(op.CurrentOffset)) != nil
				constantSuper := nativeEnumConstantSuperOwned(p, obj, name, desc, call.Name, call.Description, int(op.CurrentOffset))
				anonymousSuper := nativeAnonymousBridgeSuperOwned(p, obj, name, desc, call.Name, call.Description, int(op.CurrentOffset), work)
				if !allocation && !super && !rootSuper && !constantSuper && !anonymousSuper {
					return false
				}
				if p.bridgeCalls == nil {
					p.bridgeCalls = map[string]int{}
				}
				p.bridgeCalls[call.Name+call.Description]++
			}
		}
	}
	return true
}
func nativeMemberStaticBridgeSource(plan *nativeMemberAllocation, args []class_context.SourceCaptureOperand, ctx, binding *class_context.ClassContext, p *nativeMemberFamily) (string, bool) {
	fail := func() (string, bool) {
		if p != nil {
			p.failed = true
		}
		return "", false
	}
	if plan == nil || plan.child == nil || p == nil || ctx == nil || binding == nil {
		return fail()
	}
	bridge := plan.child.accessBridges[plan.descriptor]
	if bridge == nil || len(args) == 0 {
		return fail()
	}
	if !nativeMemberBridgeSourceDummy(args[len(args)-1].Value) {
		return fail()
	}
	invoke := &values.FunctionCallExpression{ClassName: strings.ReplaceAll(plan.child.object.GetClassName(), "/", "."), FunctionName: "<init>", Descriptor: bridge.target, Kind: values.InvokeSpecial, IsSpecialInvoke: true, HasOriginPC: true, OriginPC: plan.invokePC}
	for _, arg := range args[:len(args)-1] {
		v, ok := arg.Value.(values.JavaValue)
		if !ok {
			return fail()
		}
		invoke.Arguments = append(invoke.Arguments, v)
	}
	mt, e := types.ParseMethodDescriptor(bridge.target)
	if e != nil || len(mt.FunctionType().ParamTypes) != len(invoke.Arguments) {
		return fail()
	}
	invoke.FuncType = mt.FunctionType()
	allocationBinding := *ctx
	allocationBinding.InvocationMetadata = binding.InvocationMetadata
	allocationBinding.SiblingClassSig = binding.SiblingClassSig
	arguments := invoke.ArgumentStrings(&allocationBinding)
	name := ctx.ShortTypeName(invoke.ClassName)
	node := &values.NewExpression{JavaType: types.NewJavaClass(invoke.ClassName), ConstructorCall: invoke}
	diamond := node.SourceConstructorDiamond(&allocationBinding)
	source := "new " + name + diamond + "(" + strings.Join(arguments, ",") + ")" + nativeMemberConstructorRegistration(p, plan.child.object.GetClassName(), plan.descriptor)
	if diamond != "" {
		return nativeMemberErasedAllocation(p, plan.child, source)
	}
	return source, true
}

// Original archive users of a marker must all remain inside the committed
// lexical family. Method handles and source-spellable marker declarations are
// not unused compiler arguments, even when their erasures happen to match.
func (z *JarFS) nativeMemberJointBridgeReferencesClosed(p *nativeMemberFamily, index *nativeMemberIndex, work *workbudget.Budget) bool {
	markers := map[string]bool{}
	for _, bridges := range p.bridgeOwners() {
		for _, bridge := range bridges {
			markers[bridge.marker] = true
		}
	}
	users := map[string]bool{}
	for marker := range markers {
		for user := range index.typeUsers[marker] {
			users[user] = true
		}
	}
	for user := range users {
		if !nativeProofWork(work, 1) {
			return false
		}
		var localObject *ClassObject
		if local := p.methodLocals[user]; local != nil {
			if local.object == nil || local.object.GetClassName() != user {
				return false
			}
			if _, known := nativeMemberJointMethodLocalOwner(p, local.object, work); !known {
				return false
			}
			localObject = local.object
		}
		if user != p.owner && p.children[user] == nil && p.anonymousUnits[user] == nil && p.emptyMarkers[user] == nil && p.enumConstants[user] == nil && localObject == nil && !nativeMemberJointSwitchTableMarker(p, user, work) {
			return false
		}
		raw, ok := z.enumSiblingResolver()(user)
		if !ok {
			return false
		}
		reader := z.nativeMemberReader(nil)
		obj, err := reader.parseResolved(raw)
		if err != nil || obj.GetClassName() != user {
			return false
		}
		// Inspect marker uses on the very original local object whose scope
		// and capture packet were proved. All ordinary symbolic/declaration
		// and opcode restrictions below still apply to this participant.
		if localObject != nil {
			obj = localObject
		}
		// A marker can also be a real anonymous enclosing scope. Compose
		// its committed forest proof with the bridge proof on the same
		// original object; a freshly parsed name alone grants no scope.
		forest := p.anonymousForest
		if forest != nil && forest.members == p && forest.objects[user] != nil &&
			(user == p.owner || p.children[user] != nil || nativeMemberJointAnonymousAccess(p, user, work)) {
			obj = forest.objects[user]
		} else {
			forest = nil
		}
		if !nativeMemberBridgeMarkerAttributesClosed(obj, markers, work) {
			return false
		}
		allowed := nativeMemberJointBridgeNameTypes(p, obj, work)
		for i, constant := range obj.ConstantPool {
			if !nativeProofWork(work, 1) {
				return false
			}
			if nt, ok := constant.(*ConstantNameAndTypeInfo); ok && nt != nil {
				desc, known := sourceBridgeUTF8(obj, nt.DescriptorIndex)
				if !known {
					return false
				}
				for marker := range markers {
					if strings.Contains(desc, "L"+marker+";") && !allowed[i+1] &&
						!(forest != nil && forest.units[marker] != nil &&
							(nativeAnonymousForestConstructorNameType(obj, i+1, forest, work) ||
								nativeAnonymousForestEnclosingNameType(obj, i+1, forest, work) ||
								nativeAnonymousForestCaptureNameType(forest, obj, i+1, work))) {
						return false
					}
				}
			}
		}
		for _, member := range append(append([]*MemberInfo{}, obj.Fields...), obj.Methods...) {
			desc, ok := sourceBridgeUTF8(obj, member.DescriptorIndex)
			if !ok {
				return false
			}
			for marker := range markers {
				if strings.Contains(desc, "L"+marker+";") && !nativeMemberJointBridgeDeclaration(p, obj, member, marker, work) &&
					!(forest != nil && forest.units[marker] != nil && nativeAnonymousForestEnclosingDeclaration(obj, member, forest, work)) {
					return false
				}
			}
		}
		for _, m := range obj.Methods {
			for _, a := range m.Attributes {
				code, ok := a.(*CodeAttribute)
				if !ok {
					continue
				}
				if !nativeProofWork(work, int64(len(code.Code))) {
					return false
				}
				d := core.NewDecompiler(code.Code, func(i int) values.JavaValue { return GetValueFromCP(obj.ConstantPool, i) })
				d.Work = work
				if d.ParseOpcode() != nil {
					return false
				}
				for _, op := range d.Opcodes() {
					var name string
					var known bool
					switch op.Instr.OpCode {
					case core.OP_NEW, core.OP_CHECKCAST, core.OP_INSTANCEOF, core.OP_ANEWARRAY, core.OP_MULTIANEWARRAY:
						if len(op.Data) < 2 {
							return false
						}
						name, known = sourceBridgeClassName(obj, core.Convert2bytesToInt(op.Data[:2]))
					case core.OP_LDC:
						if len(op.Data) != 1 {
							return false
						}
						name, known = sourceBridgeClassName(obj, uint16(op.Data[0]))
					case core.OP_LDC_W:
						if len(op.Data) != 2 {
							return false
						}
						name, known = sourceBridgeClassName(obj, core.Convert2bytesToInt(op.Data))
					}
					if known && markers[name] {
						var child *nativeAnonymousClass
						if p.anonymous != nil {
							child = p.anonymous.children[name]
						}
						if op.Instr.OpCode != core.OP_NEW || user != p.owner || child == nil || child.newPC != int(op.CurrentOffset) {
							return false
						}
					}
				}
			}
		}
	}
	return true
}

// Even an otherwise valid bridge descriptor cannot stand for a source type in
// bounds or annotations. Those paths are independent from a Methodref alias.
func nativeMemberBridgeMarkerAttributesClosed(obj *ClassObject, markers map[string]bool, work *workbudget.Budget) bool {
	check := func(attrs []AttributeInfo) bool {
		bad := false
		if !nativeAnnotationDependencies(attrs, work, func(n string) {
			if markers[n] {
				bad = true
			}
		}) || bad {
			return false
		}
		for _, a := range attrs {
			if sig, ok := a.(*SignatureAttribute); ok {
				if sig == nil {
					return false
				}
				text, ok := sourceBridgeUTF8(obj, sig.SignatureIndex)
				if !ok || !nativeProofWork(work, int64(len(text))) {
					return false
				}
				names, ok := types.SignatureClassReferences(text)
				if !ok {
					return false
				}
				for _, n := range names {
					if markers[n] {
						return false
					}
				}
			}
		}
		return true
	}
	if obj == nil || !check(obj.Attributes) {
		return false
	}
	for _, m := range append(append([]*MemberInfo{}, obj.Fields...), obj.Methods...) {
		if m == nil || !check(m.Attributes) {
			return false
		}
	}
	return true
}

func nativeMemberConstructorForAllocation(child *nativeMemberClass, desc string) *nativeMemberConstructor {
	if child == nil {
		return nil
	}
	if bridge := child.accessBridges[desc]; bridge != nil {
		return child.constructors[bridge.target]
	}
	return child.constructors[desc]
}
func nativeMemberBridgeSourceDummy(value any) bool {
	v, ok := value.(values.JavaValue)
	if !ok {
		return false
	}
	literal, ok := values.UnpackSoltValue(v).(*values.JavaLiteral)
	return ok && literal != nil && literal.Data == "null" && len(literal.Units) == 0
}

// A required diamond types constructor SAM operands, but must not introduce
// target-type constraints on the allocation result. NEW carries the original
// class erasure. Cast only to that same proved allocated class: the cast cannot
// fail, repeats no operands, and preserves enclosing-instance evaluation and
// private constructor binding. In particular, a method T and a member T are
// distinct variables even if their names match.
func nativeMemberErasedAllocation(p *nativeMemberFamily, child *nativeMemberClass, source string) (string, bool) {
	if p == nil || child == nil || child.object == nil {
		return "", false
	}
	name, ok := p.sourceName(child.object.GetClassName())
	if !ok {
		p.failed = true
		return "", false
	}
	return "((" + name + ")(" + source + "))", true
}

// Source projection may discard only the original constructor's enclosing
// parameter, registered by prepareNativeMemberConstructor. A nullable value
// in that parameter remains valid; a literal null or another expression does
// not acquire the parameter's identity merely by having its erased type.
func nativeMemberSourceEnclosingParameter(value any, ctx *class_context.ClassContext, owner string) bool {
	v, ok := value.(values.JavaValue)
	if !ok || ctx == nil {
		return false
	}
	ref, ok := values.UnpackSoltValue(v).(*values.JavaRef)
	return ok && ref != nil && ref.Id != nil && ref.IsParam && !ref.IsThis && ref.CustomValue == nil && ref.StackVar == nil && ctx.LocalNames[ref.Id] == ctx.ShortTypeName(strings.ReplaceAll(owner, "/", "."))+".this"
}

// The anonymous constructor packet already proves capture stores, the original
// uninitialized THIS and the exact first SUPER invocation. That same packet can
// own a private constructor bridge; arbitrary later calls, another declaration
// instance or a flat terminal sibling cannot borrow this lexical permission.
func nativeAnonymousBridgeSuperOwned(p *nativeMemberFamily, object *ClassObject, method, descriptor, target, physical string, pc int, work *workbudget.Budget) bool {
	if p == nil || object == nil || method != "<init>" || !nativeProofWork(work, 1) {
		return false
	}
	group := p.anonymousUnits[object.GetClassName()]
	if group == nil {
		return false
	}
	unit := group.children[object.GetClassName()]
	if unit == nil || unit.object != object || unit.descriptor != descriptor || unit.superPC != pc || unit.superDescriptor != physical || object.GetSupperClassName() != target {
		return false
	}
	bridge := p.constructorBridges(target)[physical]
	if bridge == nil {
		return false
	}
	sourceDescriptor := bridge.target
	if unit.memberSuper != nil {
		// A nonstatic member constructor has a physical enclosing-instance
		// word that its source declaration omits. Compare through the original
		// member packet; descriptor equality alone conflates these bindings.
		member := unit.memberSuper
		if p.children[target] != member || member.object == nil || member.object.GetClassName() != target {
			return false
		}
		constructor := member.constructors[bridge.target]
		if constructor == nil || constructor.descriptor != bridge.target {
			return false
		}
		sourceDescriptor = constructor.sourceDescriptor
	}
	if sourceDescriptor != unit.sourceSuperDescriptor {
		return false
	}
	return group == p.anonymous && group.owner == p.owner || group == p.memberAnonymous[group.owner] || nativeMemberJointAnonymousForestOwner(p, group, work)
}
