package javaclassparser

import (
	"strings"
	"testing"
)

const nativeProtectedUnavailableFixture = `class ProtectedCallEffects{static String trace="";static int fail;static final RuntimeException failure=new RuntimeException("original");static ProtectedCallOwner receiver(ProtectedCallOwner owner){trace+="R";if(fail==1)throw failure;return owner;}static int first(int n){trace+="A";if(fail==2)throw failure;return n;}static int last(int n){trace+="B";if(fail==3)throw failure;return n;}}
class ProtectedCallOwner extends java.util.ArrayList<String>{static class Reader{void first(ProtectedCallOwner owner,int a,int b){ProtectedCallEffects.receiver(owner).removeRange(ProtectedCallEffects.first(a),ProtectedCallEffects.last(b));}void second(ProtectedCallOwner owner,int a,int b){ProtectedCallEffects.receiver(owner).removeRange(ProtectedCallEffects.first(a),ProtectedCallEffects.last(b));}}}
class ProtectedCallDerived extends ProtectedCallOwner{protected void removeRange(int a,int b){ProtectedCallEffects.trace+="D";super.removeRange(a,b);}}
class ProtectedCallDriver{public static void main(String[]args){ProtectedCallOwner.Reader reader=new ProtectedCallOwner.Reader();int rows=0;for(int method:new int[]{0,1}){ProtectedCallOwner owner=new ProtectedCallDerived();owner.addAll(java.util.Arrays.asList("a","b","c","d"));ProtectedCallEffects.fail=0;ProtectedCallEffects.trace="";if(method==0)reader.first(owner,0,2);else reader.second(owner,0,2);if(owner.size()!=2||!owner.get(0).equals("c")||!owner.get(1).equals("d")||!ProtectedCallEffects.trace.equals("RABD"))throw new AssertionError("virtual binding/argument order/once");rows++;}for(int fail:new int[]{0,1,2,3}){ProtectedCallEffects.fail=fail;ProtectedCallEffects.trace="";try{reader.first(null,0,1);throw new AssertionError("missing failure");}catch(RuntimeException e){if(fail==0?!(e instanceof NullPointerException):e!=ProtectedCallEffects.failure)throw new AssertionError("exception identity");}if(!ProtectedCallEffects.trace.equals(fail==1?"R":fail==2?"RA":"RAB"))throw new AssertionError("null check after arguments");}System.out.println(rows+":protected:inherited:virtual:arguments:bridges");}}`

const nativeProtectedParentFixture = `package probe.base;public class DispatchParent{public static final java.io.IOException failure=new java.io.IOException("original");protected Object prepare(Object token,long n)throws java.io.IOException{if(n==Long.MIN_VALUE)throw failure;return token;}protected Object prepare(String token,long n){throw new AssertionError("wrong overload");}}`
const nativeProtectedCallFixture = `package probe.access;
class ProtectedCallEffects{static String trace="";static int fail;static ProtectedCallOwner receiver(ProtectedCallOwner owner)throws java.io.IOException{trace+="R";if(fail==1)throw probe.base.DispatchParent.failure;return owner;}static Object argument(Object token)throws java.io.IOException{trace+="A";if(fail==2)throw probe.base.DispatchParent.failure;return token;}static long wide(long n)throws java.io.IOException{trace+="W";if(fail==3)throw probe.base.DispatchParent.failure;return n;}}
public class ProtectedCallOwner extends probe.base.DispatchParent{static class Reader{Object first(ProtectedCallOwner owner,Object token,long n)throws java.io.IOException{return ProtectedCallEffects.receiver(owner).prepare(ProtectedCallEffects.argument(token),ProtectedCallEffects.wide(n));}Object second(ProtectedCallOwner owner,Object token,long n)throws java.io.IOException{return ProtectedCallEffects.receiver(owner).prepare(ProtectedCallEffects.argument(token),ProtectedCallEffects.wide(n));}}}
class ProtectedCallDerived extends ProtectedCallOwner{public Object prepare(Object token,long n)throws java.io.IOException{ProtectedCallEffects.trace+="D";return super.prepare(token,n);}}
class ProtectedCallDriver{public static void main(String[]args)throws Exception{ProtectedCallOwner.Reader reader=new ProtectedCallOwner.Reader();int rows=0;for(int method:new int[]{0,1})for(Object token:new Object[]{null,new Object()}){ProtectedCallOwner owner=new ProtectedCallDerived();ProtectedCallEffects.fail=0;ProtectedCallEffects.trace="";Object result=method==0?reader.first(owner,token,7):reader.second(owner,token,7);if(result!=token||!ProtectedCallEffects.trace.equals("RAWD"))throw new AssertionError("virtual binding/erased overload/argument once");ProtectedCallEffects.trace="";try{reader.first(owner,token,Long.MIN_VALUE);throw new AssertionError("missing target failure");}catch(java.io.IOException e){if(e!=probe.base.DispatchParent.failure||!ProtectedCallEffects.trace.equals("RAWD"))throw new AssertionError("target checked identity");}rows++;}for(int fail:new int[]{0,1,2,3}){ProtectedCallEffects.fail=fail;ProtectedCallEffects.trace="";try{reader.first(null,null,1);throw new AssertionError("missing failure");}catch(Exception e){if(fail==0?!(e instanceof NullPointerException):e!=probe.base.DispatchParent.failure)throw new AssertionError("exception identity");}if(!ProtectedCallEffects.trace.equals(fail==1?"R":fail==2?"RA":"RAW"))throw new AssertionError("null check after arguments");}System.out.println(rows+":protected:inherited:virtual:arguments:bridges");}}`

func TestNativeProtectedCallRoundTrip(t *testing.T) {
	testNativePrivateSetterSourceFixture(t, map[string]string{"probe/base/DispatchParent.java": nativeProtectedParentFixture, "probe/access/ProtectedCallOwner.java": nativeProtectedCallFixture}, "probe/access/ProtectedCallOwner", "probe.access.ProtectedCallDriver", "4:protected:inherited:virtual:arguments:bridges\n")
}
func TestNativeProtectedCallRenamedRoundTrip(t *testing.T) {
	f := strings.ReplaceAll(nativeProtectedCallFixture, "ProtectedCallOwner", "OtherInheritedDispatchScope")
	testNativePrivateSetterSourceFixture(t, map[string]string{"probe/base/DispatchParent.java": nativeProtectedParentFixture, "probe/access/OtherInheritedDispatchScope.java": f}, "probe/access/OtherInheritedDispatchScope", "probe.access.ProtectedCallDriver", "4:protected:inherited:virtual:arguments:bridges\n")
}

func TestNativeProtectedWideCallRoundTrip(t *testing.T) {
	parent := `package probe.base;public class DispatchParent{protected long number(long n){return n;}protected double number(double n){return n;}}`
	source := `package probe.access;public class WideProtectedOwner extends probe.base.DispatchParent{static class Reader{long number(WideProtectedOwner owner,long n){return owner.number(n);}double bits(WideProtectedOwner owner,double n){return owner.number(n);}}}
class WideProtectedDerived extends WideProtectedOwner{public long number(long n){return super.number(n)^Long.MIN_VALUE;}}
class WideProtectedDriver{public static void main(String[]args){WideProtectedOwner owner=new WideProtectedDerived();WideProtectedOwner.Reader reader=new WideProtectedOwner.Reader();int rows=0;for(long n:new long[]{Long.MIN_VALUE,-1,0,1,Long.MAX_VALUE}){if(reader.number(owner,n)!=(n^Long.MIN_VALUE))throw new AssertionError("wide virtual binding/overflow");rows++;}for(long bits:new long[]{0,Long.MIN_VALUE,0x7ff0000000000001L,0x7ff8000000000001L,0xfff0000000000000L}){double n=Double.longBitsToDouble(bits);if(Double.doubleToRawLongBits(reader.bits(owner,n))!=bits)throw new AssertionError("original FP payload/negative zero");rows++;}try{reader.bits(null,1);throw new AssertionError("missing null failure");}catch(NullPointerException expected){}System.out.println(rows+":protected:wide:virtual:raw:bits");}}`
	testNativePrivateSetterSourceFixture(t, map[string]string{"probe/base/DispatchParent.java": parent, "probe/access/WideProtectedOwner.java": source}, "probe/access/WideProtectedOwner", "probe.access.WideProtectedDriver", "10:protected:wide:virtual:raw:bits\n")
}
